# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-lint-and-test:
    docker: # use the Docker executor
      - image: circleci/rust
        auth:
          username: rfrazier716
          password: $DOCKER_API_KEY

    environment:
        # Fail the build if there are warnings
        RUSTFLAGS: '-D warnings'
        
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version

      - run:
          name: Create Lock
          command: cargo generate-lockfile

      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - run:
          name: Build all targets
          command: cargo build

      - run:
          name: Install Clippy
          command: rustup component add clippy

      - run:
          name: Lint Source
          command: cargo clippy -- -D warnings

      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      
      - run:
          name: Run unit tests
          command: cargo test --lib

      - persist_to_workspace:
          root: ./
          paths:
            - Cargo.lock

  integration-tests:
    docker: # use the Docker executor
      - image: circleci/rust
        auth:
          username: rfrazier716
          password: $DOCKER_API_KEY
      - image: circleci/mongo:4.4
        auth:
          username: rfrazier716
          password: $DOCKER_API_KEY
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    environment:
        # Fail the build if there are warnings
        RUSTFLAGS: '-D warnings'

    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version

      - attach_workspace:
          at: ./

      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - run:
          name: Built all targets
          command: cargo build
      
      - run: 
          name: Run all tests
          command: cargo test

  format:
    docker: # use the Docker executor
      - image: circleci/rust
        auth:
          username: rfrazier716
          password: $DOCKER_API_KEY
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install formatter
          command: rustup component add rustfmt
      - run:
          name: Formatting
          command: cargo fmt --all -- --check

  audit:
    docker: # use the Docker executor
      - image: circleci/rust
        auth:
          username: rfrazier716
          password: $DOCKER_API_KEY
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Cache permission
          command: |
            sudo chown -R $(whoami):$(id -ng) /usr/local/cargo
      - restore_cache:
          keys:
            - cargo-audit-{{ arch }}
      - run:
          name: Install dependency auditing tool
          command: cargo install cargo-audit

      - save_cache:
          paths:
            - /usr/local/cargo
          key: cargo-audit-{{ arch }}

      - run:
          name: Check for known security issues in dependencies
          command: cargo audit

workflows:
  version: 2
  build-test:
    jobs:
      - build-lint-and-test:
          filters:
            tags:
              only: /.*/
      - integration-tests:
        # Integration tests should only run on main and development commits
          requires:
            - build-lint-and-test
          filters:
            branches:
              only: /^(main|development)$/  
      - format:
          filters:
            tags:
              only: /.*/
      - audit:
          filters:
            tags:
              only: /.*/